version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
