version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5090:5090"
    environment:
      - PORT=5090
      - MONGO_URI=mongodb+srv://Yossef:SGyp7BzbJyNQlfq8@cluster0.xr1yn.mongodb.net/timecapsule?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=1e90c5759696172d5a4447dfd5400fd3f888fa14636da7bdf785f527e3156d5a
      - JWT_REFRESH_SECRET=05b50a10117c55c3ca63f6dfa0fcdc28a369db326bffd060688f45e78822aeb0cb8ddf91d20e2198472e39be0dfdd6568244ed3840f92c604b87c63d2d967d18
      - BASE_URL=http://localhost:5090
      - EMAIL_HOST=live.smtp.mailtrap.io
      - EMAIL_PORT=587
      - EMAIL_USER=smtp@mailtrap.io
      - EMAIL_PASS=bc54973078df742530a307882dc6df41
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
